artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/Balkrishna1Tiwari/Name_Entity_Recognition2/d6a334d833a19951edb7ddedb6636c4cde54ee06/conll2003.zip
  local_data_file: artifacts/data_ingestion/conll2003_dataset.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ['test.csv', 'train.csv', 'valid.csv']



data_transformation:
  root_dir: artifacts/data_transformation
  tokenizer_path: artifacts/data_transformation/tokenizer
  data_path_train: artifacts/data_ingestion/conll2003/train.csv
  data_path_test:  artifacts/data_ingestion/conll2003/test.csv
  data_path_val:   artifacts/data_ingestion/conll2003/valid.csv
  tokenizer_name: "bert-base-uncased"
  

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts\data_transformation\train_transformed.csv
  test_data_path: artifacts\data_transformation\test_transformed.csv
  val_data_path: artifacts\data_transformation\val_transformed.csv
  model_ckpt: "bert-base-uncased"
  num_labels: 9
  
model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts\data_transformation\val_transformed.csv
  model_path: artifacts/model_trainer
  tokenizer_path: artifacts/data_transformation/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv
